name:                lambda-heights-client
version:             1.2.0
github:              "morgenthum/lambda-heights"
license:             BSD3
author:              "Mario Morgenthum"
maintainer:          "mario.morgenthum@gmail.com"
copyright:           "2019 Mario Morgenthum"

description:         Please see the README on GitHub at <https://github.com/morgenthum/lambda-heights#readme>

dependencies:
- async >= 2.2.1
- base >=4.7 && <5
- bytestring >= 0.10.8.2
- directory >= 1.3.3.0
- extra >= 1.6.14
- file-embed >= 0.0.11
- lambda-heights-core
- linear >= 1.20.8
- matrix >= 0.3.6.1
- mtl >= 2.2.2
- serialise >= 0.2.1.0
- sdl2 >= 2.4.1.0
- sdl2-gfx >= 0.2
- sdl2-ttf >= 2.1.0
- split >= 0.2.3.3
- stm >= 2.5.0.0
- text >= 1.2.3.1
- time >= 1.8.0.2
- vector >= 0.12.0.2
- yaml >= 0.11.0.0

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -O2
